//BASE NUMBER THAT CAN BE USED AS A STARTING COORDINATE FOR THE CANVAS
const X_START = 150;
const Y_START = 150;

//THE HEIGHT AND WIDTH OF THE CANVAS IN THE HTML
const CANVAS_WIDTH = 1000;
const CANVAS_HEIGHT = 500;

const PLAYER_WIDTH = 5;
const PLAYER_HEIGHT = 5;

export {
  X_START,
  Y_START,
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  PLAYER_WIDTH,
  PLAYER_HEIGHT,
};
