// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'top_buffer': string;
  'vert_20': string;
}
export const cssExports: CssExports;
export default cssExports;
