// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app_container': string;
  'center_col': string;
  'center_relative': string;
  'top_buffer': string;
  'vert_20': string;
}
export const cssExports: CssExports;
export default cssExports;
