// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app_container': string;
  'center_col': string;
  'center_relative': string;
  'init_btn_center': string;
  'mode_list_item': string;
  'no_padding': string;
  'play_button': string;
  'sep_xs': string;
  'top_buffer': string;
  'vert_20': string;
}
export const cssExports: CssExports;
export default cssExports;
